#!/usr/bin/env bash

set -x 
set -e

REPO=$1

./poll $REPO

mkdir -p patched/$REPO
cp tmp/$REPO/.version patched/$REPO/.version

[ -n "`git status --porcelain`" ] || exit 0

./init

./fetch $REPO

rm -rf patched/$REPO
mkdir -p patched/$REPO
cp tmp/$REPO/.version patched/$REPO/.version

for f in bin/$REPO/*
do
    [ -x $f ] && echo $f
done

echo -n "Patched $REPO " > tmp/.commit_msg
printf "%s" $(< tmp/$REPO/.version) >> tmp/.commit_msg
