#!/usr/bin/env bash

set -x 
set -e

REPO=$1

./poll $REPO

mkdir -p patched/$REPO
cp tmp/$REPO/.version patched/$REPO/.version

[ -n "`git status --porcelain`" ] 

./fetch $REPO

rm -rf patched/$REPO
mkdir -p patched/$REPO
cp tmp/$REPO/.version patched/$REPO/.version

for f in bin/$REPO/*
do
    [ -x $f ] && $f
done

echo -n "$REPO-" > tmp/.commit_msg
cat tmp/$REPO/.version >> tmp/.commit_msg
