name: cascadia-code

on:
  schedule:
    - cron:  '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init
        run: ./init.sh
      - name: Poll & patch
        run: ./patch.sh microsoft/cascadia-code
      - name: Commit & push
        run: ./push.sh 