name: JetBrainsMono-version-poll

on:
  schedule:
    - cron:  '0 10 * * *'
  
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
          # token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -Ls https://api.github.com/repos/JetBrains/JetBrainsMono/releases/latest | \
          jq -r ".tag_name" > JetBrainsMono.version
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name "$GITHUB_REPOSITORY robot"
          git config user.email "$GITHUB_WORKFLOW.$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "JetBrainsMono - new release"
          git push