name: JetBrainsMono

on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Poll & patch
        run: ./patch JetBrains/JetBrainsMono
      - name: Commit & push
        run: ./push 